### ISSUE TITLE
Get Jupyterhub service auto starting

### ISSUE THREAD

**Issue by JoshuaSBrown** [JoshuaSBrown/JH-Kubernetes-vagrant#1]
Our first objective is to get jupyterhub up and running. The server needs to be running accessible through http from the host.

**Comment by JoshuaSBrown** [comment]
1. Jupyterhub does not start on vagrant up. It is installed but not running.

**Comment by JoshuaSBrown** [comment]
First error occurs when we run 
/usr/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
which is also in the `jupyterhub.service` file

```
[I 2017-11-30 23:26:00.732 JupyterHub app:834] Loading cookie_secret from /home/vagrant/jupyterhub_cookie_secret
[W 2017-11-30 23:26:00.760 JupyterHub auth:97] whitelist contains single-character names: ['a', 'g', 'n', 'r', 't', 'v']; did you mean set(['agnrtv']) instead of set('agnrtv')?
[E 2017-11-30 23:26:00.806 JupyterHub app:1004] Error adding user r already in db
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1002, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 489, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User r does not exist.'

[W 2017-11-30 23:26:00.808 JupyterHub app:1016]
    You can set
        c.Authenticator.delete_invalid_users = True
    to automatically delete users from the Hub database that no longer pass
    Authenticator validation,
    such as when user accounts are deleted from the external system
    without notifying JupyterHub.

[E 2017-11-30 23:26:00.808 JupyterHub app:1004] Error adding user g already in db
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1002, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 489, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User g does not exist.'

[W 2017-11-30 23:26:00.808 JupyterHub app:1016]
    You can set
        c.Authenticator.delete_invalid_users = True
    to automatically delete users from the Hub database that no longer pass
    Authenticator validation,
    such as when user accounts are deleted from the external system
    without notifying JupyterHub.

[E 2017-11-30 23:26:00.808 JupyterHub app:1004] Error adding user t already in db
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1002, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 489, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User t does not exist.'

[W 2017-11-30 23:26:00.809 JupyterHub app:1016]
    You can set
        c.Authenticator.delete_invalid_users = True
    to automatically delete users from the Hub database that no longer pass
    Authenticator validation,
    such as when user accounts are deleted from the external system
    without notifying JupyterHub.

[E 2017-11-30 23:26:00.809 JupyterHub app:1004] Error adding user v already in db
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1002, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 489, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User v does not exist.'


[W 2017-11-30 23:26:00.809 JupyterHub app:1016]
    You can set
        c.Authenticator.delete_invalid_users = True
    to automatically delete users from the Hub database that no longer pass
    Authenticator validation,
    such as when user accounts are deleted from the external system
    without notifying JupyterHub.

[E 2017-11-30 23:26:00.809 JupyterHub app:1004] Error adding user n already in db
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1002, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 489, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User n does not exist.'

[W 2017-11-30 23:26:00.810 JupyterHub app:1016]
    You can set
        c.Authenticator.delete_invalid_users = True
    to automatically delete users from the Hub database that no longer pass
    Authenticator validation,
    such as when user accounts are deleted from the external system
    without notifying JupyterHub.

[E 2017-11-30 23:26:00.810 JupyterHub app:1004] Error adding user a already in db
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1002, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 489, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User a does not exist.'

[W 2017-11-30 23:26:00.810 JupyterHub app:1016]
    You can set
        c.Authenticator.delete_invalid_users = True
    to automatically delete users from the Hub database that no longer pass
    Authenticator validation,
    such as when user accounts are deleted from the external system
    without notifying JupyterHub.

[E 2017-11-30 23:26:00.820 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1382, in initialize
        yield self.init_spawners()
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1210, in init_spawners
        self.users[orm_user.id] = user = User(orm_user, self.tornado_settings)
      File "/usr/lib/python3.4/site-packages/jupyterhub/user.py", line 178, in __init__
        self.spawners[name] = self._new_spawner(name)
      File "/usr/lib/python3.4/site-packages/jupyterhub/user.py", line 208, in _new_spawner
        spawner = spawner_class(**spawn_kwargs)
      File "/usr/lib/python3.4/site-packages/traitlets/config/configurable.py", line 84, in __init__
        self.config = config
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 585, in __set__
        self.set(obj, value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 574, in set
        obj._notify_trait(self.name, old_value, new_value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 1139, in _notify_trait
        type='change',
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 1176, in notify_change
        c(change)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 819, in compatible_observer
        return func(self, change)
      File "/usr/lib/python3.4/site-packages/traitlets/config/configurable.py", line 186, in _config_changed
        self._load_config(change.new, traits=traits, section_names=section_names)
      File "/usr/lib/python3.4/site-packages/traitlets/config/configurable.py", line 153, in _load_config
        setattr(self, name, deepcopy(config_value))
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 585, in __set__
        self.set(obj, value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 559, in set
        new_value = self._validate(obj, value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 591, in _validate
        value = self.validate(obj, value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 2324, in validate
        value = super(List, self).validate(obj, value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 2242, in validate
        value = self.validate_elements(obj, value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 2321, in validate_elements
        return super(List, self).validate_elements(obj, value)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 2254, in validate_elements
        self.element_error(obj, v, self._trait)
      File "/usr/lib/python3.4/site-packages/traitlets/traitlets.py", line 2233, in element_error
        raise TraitError(e)
    traitlets.traitlets.TraitError: Element of the 'profiles' trait of a ProfilesSpawner instance must be a tuple, but
a value of ('Docker Python 2/3', 'systemuser', 'dockerspawner.SystemUserSpawner', {'container_image': 'jupyterhub/syste
muser'}) <class 'tuple'> was specified.

```

**Comment by JoshuaSBrown** [comment]
This problem for some reason appears to occur because of the following line in the jupyterhub_config.py file
`c.JupyterHub.spawner_class = 'wrapspawner.ProfilesSpawner'`

**Comment by JoshuaSBrown** [comment]
It appears that jupyterhub cannot start as a service because it tries to create a file here "/jupyterhub_cookie_secret"

**Comment by JoshuaSBrown** [comment]
Fixing the location at which jupyterhub looks for the cookie secret file helps by changing the line 
c.Jupyterhub.cookie_secret_file = '/home/vagrant/jupyterhub_cookie_secret'

**Comment by JoshuaSBrown** [comment]
Finally, the problem originates because the service was running as user=vagrant as opposed to root need to edit the jupyterhub.service file and delete the line that says user=vagrant

**Comment by JoshuaSBrown** [comment]
Ok, now it is starting automatically, but nothing is showing up when I access port 8000

**Comment by JoshuaSBrown** [comment]
Ok Comment everything out and it will show the login page we will start from there.
